// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Doctor is the predicate function for doctor builders.
type Doctor func(*sql.Selector)

// Office is the predicate function for office builders.
type Office func(*sql.Selector)

// Specialist is the predicate function for specialist builders.
type Specialist func(*sql.Selector)

// Working is the predicate function for working builders.
type Working func(*sql.Selector)
