// Code generated by entc, DO NOT EDIT.

package department

const (
	// Label holds the string label denoting the department type in the database.
	Label = "department"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDname holds the string denoting the dname field in the database.
	FieldDname = "dname"

	// Table holds the table name of the department in the database.
	Table = "departments"
)

// Columns holds all SQL columns for department fields.
var Columns = []string{
	FieldID,
	FieldDname,
}

var (
	// DnameValidator is a validator for the "dname" field. It is called by the builders before save.
	DnameValidator func(string) error
)
