// Code generated by entc, DO NOT EDIT.

package office

const (
	// Label holds the string label denoting the office type in the database.
	Label = "office"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFname holds the string denoting the fname field in the database.
	FieldFname = "fname"

	// Table holds the table name of the office in the database.
	Table = "offices"
)

// Columns holds all SQL columns for office fields.
var Columns = []string{
	FieldID,
	FieldFname,
}

var (
	// FnameValidator is a validator for the "fname" field. It is called by the builders before save.
	FnameValidator func(string) error
)
