// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/Piichet/app/ent/specialist"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Specialist is the model entity for the Specialist schema.
type Specialist struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Sname holds the value of the "sname" field.
	Sname string `json:"sname,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Specialist) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // sname
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Specialist fields.
func (s *Specialist) assignValues(values ...interface{}) error {
	if m, n := len(values), len(specialist.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field sname", values[0])
	} else if value.Valid {
		s.Sname = value.String
	}
	return nil
}

// Update returns a builder for updating this Specialist.
// Note that, you need to call Specialist.Unwrap() before calling this method, if this Specialist
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Specialist) Update() *SpecialistUpdateOne {
	return (&SpecialistClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Specialist) Unwrap() *Specialist {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Specialist is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Specialist) String() string {
	var builder strings.Builder
	builder.WriteString("Specialist(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", sname=")
	builder.WriteString(s.Sname)
	builder.WriteByte(')')
	return builder.String()
}

// Specialists is a parsable slice of Specialist.
type Specialists []*Specialist

func (s Specialists) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
