// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Piichet/app/ent/specialist"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// SpecialistCreate is the builder for creating a Specialist entity.
type SpecialistCreate struct {
	config
	mutation *SpecialistMutation
	hooks    []Hook
}

// SetSname sets the sname field.
func (sc *SpecialistCreate) SetSname(s string) *SpecialistCreate {
	sc.mutation.SetSname(s)
	return sc
}

// Mutation returns the SpecialistMutation object of the builder.
func (sc *SpecialistCreate) Mutation() *SpecialistMutation {
	return sc.mutation
}

// Save creates the Specialist in the database.
func (sc *SpecialistCreate) Save(ctx context.Context) (*Specialist, error) {
	if _, ok := sc.mutation.Sname(); !ok {
		return nil, &ValidationError{Name: "sname", err: errors.New("ent: missing required field \"sname\"")}
	}
	if v, ok := sc.mutation.Sname(); ok {
		if err := specialist.SnameValidator(v); err != nil {
			return nil, &ValidationError{Name: "sname", err: fmt.Errorf("ent: validator failed for field \"sname\": %w", err)}
		}
	}
	var (
		err  error
		node *Specialist
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SpecialistMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SpecialistCreate) SaveX(ctx context.Context) *Specialist {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *SpecialistCreate) sqlSave(ctx context.Context) (*Specialist, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *SpecialistCreate) createSpec() (*Specialist, *sqlgraph.CreateSpec) {
	var (
		s     = &Specialist{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: specialist.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: specialist.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Sname(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: specialist.FieldSname,
		})
		s.Sname = value
	}
	return s, _spec
}
