// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/Piichet/app/ent/predicate"
	"github.com/Piichet/app/ent/working"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// WorkingUpdate is the builder for updating Working entities.
type WorkingUpdate struct {
	config
	hooks      []Hook
	mutation   *WorkingMutation
	predicates []predicate.Working
}

// Where adds a new predicate for the builder.
func (wu *WorkingUpdate) Where(ps ...predicate.Working) *WorkingUpdate {
	wu.predicates = append(wu.predicates, ps...)
	return wu
}

// SetAddedTime sets the added_time field.
func (wu *WorkingUpdate) SetAddedTime(t time.Time) *WorkingUpdate {
	wu.mutation.SetAddedTime(t)
	return wu
}

// Mutation returns the WorkingMutation object of the builder.
func (wu *WorkingUpdate) Mutation() *WorkingMutation {
	return wu.mutation
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (wu *WorkingUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wu.hooks) == 0 {
		affected, err = wu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WorkingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wu.mutation = mutation
			affected, err = wu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wu.hooks) - 1; i >= 0; i-- {
			mut = wu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WorkingUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WorkingUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WorkingUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wu *WorkingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   working.Table,
			Columns: working.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: working.FieldID,
			},
		},
	}
	if ps := wu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.AddedTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: working.FieldAddedTime,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{working.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// WorkingUpdateOne is the builder for updating a single Working entity.
type WorkingUpdateOne struct {
	config
	hooks    []Hook
	mutation *WorkingMutation
}

// SetAddedTime sets the added_time field.
func (wuo *WorkingUpdateOne) SetAddedTime(t time.Time) *WorkingUpdateOne {
	wuo.mutation.SetAddedTime(t)
	return wuo
}

// Mutation returns the WorkingMutation object of the builder.
func (wuo *WorkingUpdateOne) Mutation() *WorkingMutation {
	return wuo.mutation
}

// Save executes the query and returns the updated entity.
func (wuo *WorkingUpdateOne) Save(ctx context.Context) (*Working, error) {
	var (
		err  error
		node *Working
	)
	if len(wuo.hooks) == 0 {
		node, err = wuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WorkingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wuo.mutation = mutation
			node, err = wuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(wuo.hooks) - 1; i >= 0; i-- {
			mut = wuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WorkingUpdateOne) SaveX(ctx context.Context) *Working {
	w, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return w
}

// Exec executes the query on the entity.
func (wuo *WorkingUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WorkingUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wuo *WorkingUpdateOne) sqlSave(ctx context.Context) (w *Working, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   working.Table,
			Columns: working.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: working.FieldID,
			},
		},
	}
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Working.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := wuo.mutation.AddedTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: working.FieldAddedTime,
		})
	}
	w = &Working{config: wuo.config}
	_spec.Assign = w.assignValues
	_spec.ScanValues = w.scanValues()
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{working.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return w, nil
}
