// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/Piichet/app/ent/working"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Working is the model entity for the Working schema.
type Working struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AddedTime holds the value of the "added_time" field.
	AddedTime time.Time `json:"added_time,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Working) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
		&sql.NullTime{},  // added_time
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Working fields.
func (w *Working) assignValues(values ...interface{}) error {
	if m, n := len(values), len(working.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	w.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field added_time", values[0])
	} else if value.Valid {
		w.AddedTime = value.Time
	}
	return nil
}

// Update returns a builder for updating this Working.
// Note that, you need to call Working.Unwrap() before calling this method, if this Working
// was returned from a transaction, and the transaction was committed or rolled back.
func (w *Working) Update() *WorkingUpdateOne {
	return (&WorkingClient{config: w.config}).UpdateOne(w)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (w *Working) Unwrap() *Working {
	tx, ok := w.config.driver.(*txDriver)
	if !ok {
		panic("ent: Working is not a transactional entity")
	}
	w.config.driver = tx.drv
	return w
}

// String implements the fmt.Stringer.
func (w *Working) String() string {
	var builder strings.Builder
	builder.WriteString("Working(")
	builder.WriteString(fmt.Sprintf("id=%v", w.ID))
	builder.WriteString(", added_time=")
	builder.WriteString(w.AddedTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Workings is a parsable slice of Working.
type Workings []*Working

func (w Workings) config(cfg config) {
	for _i := range w {
		w[_i].config = cfg
	}
}
