// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/Piichet/app/ent/working"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// WorkingCreate is the builder for creating a Working entity.
type WorkingCreate struct {
	config
	mutation *WorkingMutation
	hooks    []Hook
}

// SetAddedTime sets the added_time field.
func (wc *WorkingCreate) SetAddedTime(t time.Time) *WorkingCreate {
	wc.mutation.SetAddedTime(t)
	return wc
}

// Mutation returns the WorkingMutation object of the builder.
func (wc *WorkingCreate) Mutation() *WorkingMutation {
	return wc.mutation
}

// Save creates the Working in the database.
func (wc *WorkingCreate) Save(ctx context.Context) (*Working, error) {
	if _, ok := wc.mutation.AddedTime(); !ok {
		return nil, &ValidationError{Name: "added_time", err: errors.New("ent: missing required field \"added_time\"")}
	}
	var (
		err  error
		node *Working
	)
	if len(wc.hooks) == 0 {
		node, err = wc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WorkingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wc.mutation = mutation
			node, err = wc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(wc.hooks) - 1; i >= 0; i-- {
			mut = wc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (wc *WorkingCreate) SaveX(ctx context.Context) *Working {
	v, err := wc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wc *WorkingCreate) sqlSave(ctx context.Context) (*Working, error) {
	w, _spec := wc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	w.ID = int(id)
	return w, nil
}

func (wc *WorkingCreate) createSpec() (*Working, *sqlgraph.CreateSpec) {
	var (
		w     = &Working{config: wc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: working.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: working.FieldID,
			},
		}
	)
	if value, ok := wc.mutation.AddedTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: working.FieldAddedTime,
		})
		w.AddedTime = value
	}
	return w, _spec
}
