// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// DepartmentsColumns holds the columns for the "departments" table.
	DepartmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "dname", Type: field.TypeString},
	}
	// DepartmentsTable holds the schema information for the "departments" table.
	DepartmentsTable = &schema.Table{
		Name:        "departments",
		Columns:     DepartmentsColumns,
		PrimaryKey:  []*schema.Column{DepartmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// DoctorsColumns holds the columns for the "doctors" table.
	DoctorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// DoctorsTable holds the schema information for the "doctors" table.
	DoctorsTable = &schema.Table{
		Name:        "doctors",
		Columns:     DoctorsColumns,
		PrimaryKey:  []*schema.Column{DoctorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// OfficesColumns holds the columns for the "offices" table.
	OfficesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "fname", Type: field.TypeString},
	}
	// OfficesTable holds the schema information for the "offices" table.
	OfficesTable = &schema.Table{
		Name:        "offices",
		Columns:     OfficesColumns,
		PrimaryKey:  []*schema.Column{OfficesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// SpecialistsColumns holds the columns for the "specialists" table.
	SpecialistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sname", Type: field.TypeString},
	}
	// SpecialistsTable holds the schema information for the "specialists" table.
	SpecialistsTable = &schema.Table{
		Name:        "specialists",
		Columns:     SpecialistsColumns,
		PrimaryKey:  []*schema.Column{SpecialistsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// WorkingsColumns holds the columns for the "workings" table.
	WorkingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "added_time", Type: field.TypeTime},
	}
	// WorkingsTable holds the schema information for the "workings" table.
	WorkingsTable = &schema.Table{
		Name:        "workings",
		Columns:     WorkingsColumns,
		PrimaryKey:  []*schema.Column{WorkingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DepartmentsTable,
		DoctorsTable,
		OfficesTable,
		SpecialistsTable,
		WorkingsTable,
	}
)

func init() {
}
