// Code generated by entc, DO NOT EDIT.

package specialist

import (
	"github.com/Piichet/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Sname applies equality check predicate on the "sname" field. It's identical to SnameEQ.
func Sname(v string) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSname), v))
	})
}

// SnameEQ applies the EQ predicate on the "sname" field.
func SnameEQ(v string) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSname), v))
	})
}

// SnameNEQ applies the NEQ predicate on the "sname" field.
func SnameNEQ(v string) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSname), v))
	})
}

// SnameIn applies the In predicate on the "sname" field.
func SnameIn(vs ...string) predicate.Specialist {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Specialist(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSname), v...))
	})
}

// SnameNotIn applies the NotIn predicate on the "sname" field.
func SnameNotIn(vs ...string) predicate.Specialist {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Specialist(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSname), v...))
	})
}

// SnameGT applies the GT predicate on the "sname" field.
func SnameGT(v string) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSname), v))
	})
}

// SnameGTE applies the GTE predicate on the "sname" field.
func SnameGTE(v string) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSname), v))
	})
}

// SnameLT applies the LT predicate on the "sname" field.
func SnameLT(v string) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSname), v))
	})
}

// SnameLTE applies the LTE predicate on the "sname" field.
func SnameLTE(v string) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSname), v))
	})
}

// SnameContains applies the Contains predicate on the "sname" field.
func SnameContains(v string) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSname), v))
	})
}

// SnameHasPrefix applies the HasPrefix predicate on the "sname" field.
func SnameHasPrefix(v string) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSname), v))
	})
}

// SnameHasSuffix applies the HasSuffix predicate on the "sname" field.
func SnameHasSuffix(v string) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSname), v))
	})
}

// SnameEqualFold applies the EqualFold predicate on the "sname" field.
func SnameEqualFold(v string) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSname), v))
	})
}

// SnameContainsFold applies the ContainsFold predicate on the "sname" field.
func SnameContainsFold(v string) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSname), v))
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Specialist) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Specialist) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Specialist) predicate.Specialist {
	return predicate.Specialist(func(s *sql.Selector) {
		p(s.Not())
	})
}
