// Code generated by entc, DO NOT EDIT.

package working

const (
	// Label holds the string label denoting the working type in the database.
	Label = "working"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAddedTime holds the string denoting the added_time field in the database.
	FieldAddedTime = "added_time"

	// Table holds the table name of the working in the database.
	Table = "workings"
)

// Columns holds all SQL columns for working fields.
var Columns = []string{
	FieldID,
	FieldAddedTime,
}
